name: Scrape IMDb Top 250

on:
  schedule:
    # Runs at 00:00 UTC every day
    - cron: "0 16 * * *"
  workflow_dispatch: # Allow manual triggers

jobs:
  scrape-imdb:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Run scraper by 24ds1000021@ds.study.iitm.ac.in
        run: | # python
          uv run --with httpx,lxml,cssselect python scraper/scrape.py

      - name: Commit and push changes
        run: |
          git config --local user.email "24ds1000021@ds.study.iitm.ac.in"
          git config --local user.name "24ds1000021@ds.study.iitm.ac.in"
          git add *.json
          git commit -m "Update IMDb Top 250 data for 24ds1000021 [skip ci]" || exit 0
          git push
